apiVersion: ENC[AES256_GCM,data:owo=,iv:MrDBXc13TeoaJJLIYTPp0792BTt+dh3UxP0/r/IaXZg=,tag:yl2fmrdUXe3uD7tU8k8zyw==,type:str]
kind: ENC[AES256_GCM,data:/U3LwLAH,iv:VRS1mBqDwsLr1aXFXAej1DDl2NDzjA+ENOgzdwFM/Z8=,tag:HqCMm7K13nPXacJqZr/IbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tFOt/7V9PA==,iv:jU3WlTAFu/317jowwBFO6DdkFOHO3VAd2xcYN9ZU7Ok=,tag:QLxFooE0wYE3eRY71e0LKQ==,type:str]
    namespace: ENC[AES256_GCM,data:h/Bjz3xgzm0X7RYZOiUdmA==,iv:X3KCKgle+k6LRuK+aQBqhPfw1XeFxrQXtyj4s0Gamz4=,tag:E9mRqQEV1fPJglV8JWzG2g==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:mK9BfYYCZpDq4HCugg==,iv:XnfBkuceTOXtn5GRkehJX1YBCKCmccRBsM6xZQWbQKQ=,tag:AbAUyBYZaEP5uUw0tcqeOw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:+qfgpTGmyL8/tNRuFC7HueEnPZA5b64vn+TsZCGC8+ojhRKWl8kJS8YiKlXlcFiixpiHfP8BCkGn3x2vN8mfhw==,iv:4+oT6OR7PuwT/BmOKm7wn1JRjpkQ9tHqHyUVfv910cM=,tag:P2hb+WVv0/xW8sRCDlIg/A==,type:str]
    MB_USER_AGENT: ENC[AES256_GCM,data:1q2pqHjOK7+GSrtPOgGPe8IsnjObJTvmhyNq2em+9xL83kkSXCfEYteKIw==,iv:tiUdyqBSV87j8d2kF/a6MMU5+HRZuOiwGtUVuhbejHs=,tag:L2AnSIs80ixrAEOVlK6CPQ==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDhRU3o4Yk40c3dPbVB5
            eXJiYm5NVFdxYnJqcG5GZDRyazQ2bDFadlc4CmplQkRsTVVwelpCTGd2UjRYWGh0
            T00yK05MRmtUMC84NmtvbnBYeVdGbm8KLS0tIDJUNEFWaUpnejJhb2lKYmJTUXNt
            WXJwT0FKMWFmdkUyV3hhVFM0MGNjVEkKGWZaDj4RUD6NveCcJowl3CEn8xM1b+Em
            4TKaCZwCQPJUfyHRN1ENnpqdR+gBt+cFSudfJ5cnqlaDPaI4MLAJ/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T14:30:33Z"
    mac: ENC[AES256_GCM,data:+7ZlMfb0/8kWBNnmBltqTCtwd/7jR/djU4pCSj/It/qDLe67Np2L2Y5S0VjCFubNIzVUlmYGSfzcXhPtzq7n70MuxIeoTYok6mq+DAqb8g5jLxA0qbIdWgZyA/XWtmsggHZ6GeNL1YHQK06WtxthwTGDhTbg/Xe3xXOusTuC0z4=,iv:5bNpLIGiT1qBf5KeuqoSRBbtYXxSHthl5Sx81TN9VJk=,tag:c5Z8DFhxJESOCAbzqVm4aQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
