apiVersion: ENC[AES256_GCM,data:p44=,iv:S4ufjXh1D887VKbuRWPiJrga8oY+YISzf1JYd4HByMk=,tag:a9drJTV1USs9tJfhtf7D6A==,type:str]
kind: ENC[AES256_GCM,data:DnqTHKDV,iv:PdYBihClOhrKSteUxNwq3rwgtkEjJiLpT9jI+JodEj8=,tag:/WcFj7ALFBo8iJpAN6PR6g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mJnKM4jAtCNr0XZvvBk=,iv:9rIdjrJBMflNDJ+JX4k6Llfg0qRUBSA7HImMTC/EsIk=,tag:Sho6d6bcdIe6tl2mSASnkw==,type:str]
    namespace: ENC[AES256_GCM,data:TaEQswfA0yvkp5dsxjNUHA==,iv:EbmmWAxjavTh/XA9L2J+E1UqIzJVS8/gE3Ko5SXqqk0=,tag:NMZGFUzb8jfYUJneuJIMXg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Vm2JtpCbIhvR,iv:7A3I+oRYE5Gi5c+mCUpxbqSq/53/MTcKSTENuAVQeFc=,tag:Aj4erOC9Vm2nnXsReRRGFA==,type:str]
    password: ENC[AES256_GCM,data:4Orgw9xzIAJEGg==,iv:bvfp+zqjlIjExafZR8sncH17dt2QQazAT504P8OtHm8=,tag:FEX8HSbuaK2gbbnsX/9xHg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSVZSMUIzWTdKTWR2cWV1
            dGFSNVl2eXQyaWN4UjBvcUtmMFlvMHZjUjNVCndaTWZFd3ZHOE5vSHJQVkVRa2tE
            ZFlpM2Rsb2ZsYWVCa1lMMWZpclVXbUUKLS0tIDI2UjdOWUJrdm10cHA0ejJldkNo
            bWEwdnd1UTVqVVgzelVqWjA3SlJhY3MKPtdtYP/pg+FSEXxg011jIxz/QZB4HNzl
            b09eCuksizt2Sy9HIhsFq/mstsY41wW0msOuksZd0J2w2HZkmcEoag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T09:38:48Z"
    mac: ENC[AES256_GCM,data:itNM/V16g1mEjxk1/vE7ycNb0+DDLDrwuRXPMnU+DvxJAgf68iHiSHcyUF2cB7rd1+cnfwWUIYDYlvfVDpnuZ6AlV1u0Q6GQ522G6nhRL+BZOrjXr4095190OGNCNPJE5fPv88Q9tEwDrUa8onbJH3oiKzPHdsgEGVMEi5nSMck=,iv:8vVzdh96SiV/jncuFKoKJ0jp/K1GhmRT4wPcw3A6Mn8=,tag:D39l/6med8WFwxAWtA/xHg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
