apiVersion: ENC[AES256_GCM,data:jHY=,iv:QNJo2FnD5hdNGgwemVIdGjiWCcpKX+V+Ssg9+95v5VI=,tag:5vn/GAXkClDJ/I6uWFlv6A==,type:str]
kind: ENC[AES256_GCM,data:cTO0pBV8,iv:ybcOmoLIbQ4GFH91Y0Xo5aJ4WM3AECB3Pxq2F/gAGAU=,tag:+MlqXjaJPDI/C5FXHvfjJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:74lZbqy9aQ==,iv:3E0wqMQ+bFuiaX8+35gUNLQ1B9HSQCiXYRK3Tz6vzlA=,tag:8gxfCWnj17LtXjP0kUgmLw==,type:str]
    namespace: ENC[AES256_GCM,data:fqHEq/niIg04P5EVd+gvKg==,iv:4c4LoYAX2fvDGXU+3nksjHBN5PA3mualhO7yUeFzBRk=,tag:94vsr3vOP6nBmespFthK9w==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:RBg6ecsiIB+VDgVZ0H9w,iv:5w/pQY65eIW+Nfpw8Dl1gZw2TMWiTc2oq6OMVMNdjyM=,tag:vapxwqUSjPVZs3cxE5pPLQ==,type:str]
    PGUSER: ENC[AES256_GCM,data:AWcE0JMXW1wMOkmCvPIH,iv:pfTgd6kkAhxuTmZbfLGL0zKckYjmSf4XYl+ZvQQjMjw=,tag:T+uUWx7U4ZZ6TF3J9IFghQ==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:+eExoUBMSQB7lEH5VEk=,iv:/IbEtrucKH1HWyzFFPbQ02uab7IU/94QKU57p7i+Nzg=,tag:dQpb0egFiH4RzhaXc0xPsg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVBwcmZSc29EWDhzOWx6
            YmpKS0RQK21CQ3o3Tnl1c3NoMkFoR2lkWHpRCjhMQXdYNkVYOTdFTHdLb0QvTTZI
            UkZEL2hzcDhtcGEzN1Y0VkVLUmV1eXMKLS0tIHJ3VGZXRzliLzk3K0ZTQVBwTWJs
            SHI1WEtNRm8yc1hCZ2RNNGNuTW9MR1UKB7x8jRUhzW32yKU33JvZ5xfXtb0ocofB
            bLCFME2039hy8BqJkE5hqnN4c6PwDH+k/4I4KbCRPcDmYcfsv6MgRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T09:38:48Z"
    mac: ENC[AES256_GCM,data:DmxtQjH+WULad42Om89smMPS7EOUx8rmJUwUbZTsPaR0LiMdveRqWGGHAXfvRiQb+WzHato1khNb7KiXjaISQXnZaaS8LVawcQz6V5v73u7FZ0YDal2Lkgu2kuBMfUTYOVxddpHV240dgp4n0fZ9nNffkq3K0nB8mFPUHlBalwA=,iv:XJaFBpeaR9xmRd4sxRFMncG8Koxl0l/Pz+AO3WT75Ec=,tag:qj8qY97glkKAgkA5Olaw1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
