apiVersion: ENC[AES256_GCM,data:RSE=,iv:7Dr36YSPZMQkk7y8YR0MhWWD7QSDsoJBndnEDO91A9E=,tag:rXqDZrOth9XbKB5Btk/BdA==,type:str]
kind: ENC[AES256_GCM,data:Z6WOTlWA,iv:L61d+cpg8iFgpVAJYKs1CSBoOH3q6bdUBqhFg9C+XE0=,tag:ZiHN6WXguD1Ydp6oUzXLhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:60KyVDH6Dw==,iv:Bbf6sukrCuhHKa8vfeOmKCmDXrTIEJCZLxzUcRSu2Eg=,tag:djhmNG80cn+QTVx9LbvgZw==,type:str]
    namespace: ENC[AES256_GCM,data:RY3Rmi2ynZMyyJWR6xgKPQ==,iv:TNdGcxXLv2pYyI8H/zYA8tfXXEQBsVnJENXE3IXG6ME=,tag:oU7zP8MR4fEC/4XaMZKexQ==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:CyTviXF6mO7GvIe9lw==,iv:nSFqpyLPsCnNXYcLbQ0ftfFhDiMo48yx5NOqN4HKivg=,tag:/5UOcSqTP7FItGlgbSsyNA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:z+iw0oCEiMaAxgt+YXYUjdN7pbO5A50mbO5wXpvVVDFBppMnw7R+Fssy3MU4mn8tkc0RyOQc0LHNi3rAWANeiw==,iv:a30OFa3hibAlE3UUVW0f2Co3YjDPwoConX+WbkXI8QA=,tag:/GIuJejS7BUunrMkFpg0fg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcUdnWWluRXBBNFpWOWhy
            c2NoZ0Z0VDY4aEcxeGhTUXRURXRwY05BcUJnCk1VVnV0a1ExYmltSWlEWVMzd0ZO
            RWkyd0xtVm5RcTFvcUhiNnkzbkVWOGcKLS0tIDhXYm5qRTlZR0xuK1IyaVdaNVla
            RDZZaU8wa2l0RUdFYldDdFRWb3ByMmcKXH5jjGrfFYIAwYFildfQh+UXCZA04j/k
            N/AgzhZeklTgtLs/r0v5oXObOJTzMIJWHrpPPcTgoeQPmD5/j+yzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T09:38:48Z"
    mac: ENC[AES256_GCM,data:+CClZPyqHS27zzN4Xyzmnryh5Aa76/s9wBG/exf0gHIETP6tKvVpP4umHDZ04DgsD6idwhbBtq0Fbz8EQ7WfEP1JQwpAneNhLQr4JNde85+7GpPIkiRS8SjBOdWxQfvjWteA4OihPyGiYxHdsqZB3ouY0rDEmf+9JdQzuNJJLd4=,iv:pUh5lBG4rG34aAw+8lfzxiimu2X5pTyQgDx+Ukds5ko=,tag:Yo196HBp/AGFlKAtv0KWjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
