apiVersion: ENC[AES256_GCM,data:60E=,iv:98aRseG4fofdU4zJfYQRWJsAI5ixT9a/zZbLLxzit/I=,tag:j548SxZvB3qrhEpbLmGWzA==,type:str]
kind: ENC[AES256_GCM,data:xmSRM6oC,iv:H6rcrhAAkCfp6wtisfwnGB4CYEDsiYryeV4J0kZs2yg=,tag:ZiyCoeobT1evGe/zv6hmEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ShIkLpSg4A==,iv:lvGK5XR1TeuwJpZ/w3HYix7oYUygxQoxlBGNFJ0xjmw=,tag:nVE0zJD8d20XNvbg8Ltmmg==,type:str]
    namespace: ENC[AES256_GCM,data:/8F6m2tw4K5ON2js+oT1Cw==,iv:JsFu3S4R/e8Uit8cqUTnqlArt9hJI0jI0Dp6t638DrQ=,tag:nvutTzIN/9VDSSjOGG3pWA==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:ePtp3A//K10G8kqlQA==,iv:S9hFuPnG88T1Bzpsl3uhmwG4SWyKu8xrDRcmq+q5DvU=,tag:COf2JgtVNZj3amro/ZAqoA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:EP18tzPATAUSUTLiOqVVPCZTadfcTJGFhF8mad6Nv0F/pfhsRl+sFvTwT3pn38E6FoUy12OAV/gp3GKKHLI8gw==,iv:1zeHrKeL7sg50xiaGyKZqwwWByjXl4DoFvmDxpW/BOQ=,tag:4v7RXDhXj1zvXUzIzmPvqw==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdGVUMno2anE2RkNlYnpv
            Z3pRWFppK0JWcG43aVRiWXRnYXdYekplbHh3CmI0KzFPTmVTeGlLaEUwNlo0ajdl
            UUs3YjFQVTlWaGZ0dk9iWUNXOEp3SEkKLS0tIGlQNUNBTGxuT0F5TldxNTFuMzMz
            Y2FJN21SelhTcTg2N1QwQjJmanFBUlUK8Z2SXX4+boJu0xRs9VKlXAB5/3NxKjz7
            wtcx3tkxxT7CPIGL145RihEW8OkOGGKH4laZ4p8evSz/7L0kekZnuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:40:47Z"
    mac: ENC[AES256_GCM,data:hTqhJ/tnX7fjWbazJofXb6QHlOF6gEc0T8AGaySO4ozFf2dWiQykN6TKklGobmAE71xCuVIzbB+K0DHWd2Piq+yKA7h14iEHxtpvCZP06KwoAhHKDqTPFdw8q5KX+jO71hC9CmgHc6GkOEgskdSmn3oaR67G/ILdOCZhbsZAMPY=,iv:ReRoTuIBc/jHRDqRjlPUY6FrVHOnWmCKGEa9tDqNgwc=,tag:f22dMlOnMXQDdjMpRawsTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
