apiVersion: ENC[AES256_GCM,data:gOU=,iv:ebkIPCl1pgAWDz4C94FlqKBNDHPuxQUvuC0Y+rPAuaw=,tag:8VLIUhFX3xz467b+idH6kA==,type:str]
kind: ENC[AES256_GCM,data:O2RvFbR9,iv:cwplapEHqtXWwe41yVfqwwnpxKLGFeEhMetIrnr6ejU=,tag:93C+FsncJqgOab9OV184Kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WQEDeqg5yA==,iv:vjgoqVmjoN5BKXf+VjG2MP5pm31E4zGQ3cG8eOCTEFs=,tag:T2N3/jYXeDgRF6DRi5jVWA==,type:str]
    namespace: ENC[AES256_GCM,data:ZSB5pqAmcn+nu2oYJN0SoQ==,iv:hsTzCN1vxB/1OvQkUcCQ99kQEO5W1Bu2gs9il6d+EEc=,tag:xsxaVk16p2qf0kp/ztd3ww==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:Ep9xq/YeV4ZQp1BWG6Hm,iv:SL1TmN0P97F2iC3OX9FXDddAIQhwqnIw7kKP6nTTlQg=,tag:ruk37NA1WCAFFMiBk2QB4w==,type:str]
    PGUSER: ENC[AES256_GCM,data:kIII4YAD9vEE9W+BK5WA,iv:HRbcP/Q+sgRWSVL6g/2tjg7o31R9Xw/VMu4YgpR+qY8=,tag:rh/laYD9FnVH/G/iqO7ziA==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:PvNTqdqxASQMsSbfPLw=,iv:PZn5QbxPqv1kOb3htXn6t/k9nqGFgTgiJ6S5mI/68W8=,tag:5JBaC6zdYRr9OBfC3XstCg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSEtRUXlyd1E2TWplKzdY
            ZlZ6WEt1cjhPNjc2aVBHVStSemJXZ1JDbWtVCjk1cnhQZDgzRHRlUWlMN1krZC9u
            a3EzQm1za21iVzdUYXBXMkxteGI0bnMKLS0tIHF1TWxjdjFLVHdBNGQ4d05GMHFj
            N1RUbE05bTgzaDhwZ0VqQzFjQ05kd3cKTT/qQGdvx5wd7QAcPyckoD5TQ0kPDXjc
            qDpKvhTzRpW+T+jqF1nG8VYf24hLRUrREiiRE9SVsjg3AWfyTxCwcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T14:30:47Z"
    mac: ENC[AES256_GCM,data:7OhGeNvbAULprEg/f6VG1kuvYwSfeaelChfUOlGL30UolvK8t7sun+Mhf8W7vcqaxDOmi5N5BY3y9aQC2aVV9dI3jYNxjZ6QYC6rRW1dNyr6htYdiE0Z2d9ACoqNA8axJEtYDLcY1rsHKjcD5qdbYBCprSgTRRAil6AYr9cZ7os=,iv:GspJKxQz0YfbAoUwOy4f1lxx5nlcF+3R/LuSNT3P0bQ=,tag:Q8oq3ldqFAINwxf2GrnVCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
