apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: reimagined-disco
spec:
  selector:
    app: reimagined-disco
    component: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # must match the containerPort of the Pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: reimagined-disco
spec:
  selector:
    app: reimagined-disco
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # must match the containerPort of the Pod
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: reimagined-disco
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - music.nestix.dev
      secretName: music-nestix-dev-tls
  rules:
    - host: music.nestix.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 80
    #- host: music-api.saba.net
    #  http:
    #    paths:
    #      - path: /
    #        pathType: Prefix
    #        backend:
    #          service:
    #            name: api-svc
    #            port:
    #              number: 80