apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- storage.yaml
- ingress.yaml
- ui.yaml
- api.yaml
- postgres.yaml

images:
- name: pirraste/reimagined-disco-api
  newTag: v0.3.0
- name: pirraste/reimagined-disco-ui
  newTag: v0.3.3
