apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- storage.yaml
- ingress.yaml
- ui.yaml
- api.yaml
- postgres.yaml
- cronjob.yaml

images:
- name: pirraste/reimagined-disco-api
  newTag: v0.6.8
- name: pirraste/reimagined-disco-jobs
  newTag: v0.1.3
- name: pirraste/reimagined-disco-ui
  newTag: v0.8.1
