apiVersion: ENC[AES256_GCM,data:o60=,iv:zIVV1LzVwiGvW0SUF5m2kflwt82brIQ954eQMRPzshs=,tag:9rnC+FoalxVzAa1RusAVfQ==,type:str]
kind: ENC[AES256_GCM,data:/QOE2+16,iv:lwfH+BcLyBujXwUhwcohQJrW+hi/Q/4g3g5azw8hEV4=,tag:dE5ikm5WV+Ph1qnYMKKnCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zj11FdkcAA==,iv:JUU1WuXoUyzjBXfTGaGfcTFgN7xpniu1mDdbWtRJKOw=,tag:wC3hhQrNvoftZrFswtMpcA==,type:str]
    namespace: ENC[AES256_GCM,data:tMUJaCicV2LqucAx+F6hDA==,iv:aoGSC7DCG7Ehr1DC3McGt95KLZLBkxb6B1ZbhkuwjpI=,tag:V3zI9j1cbNqvDmN5GRvpDg==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:mwUxEoSiM2GQUQQPrw==,iv:fB0LgWttrKNax9cend3lrsp6fH/ExS+MVf+K+4EB+uQ=,tag:nhb0SACNH8YUs/Mweki9PA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:IjA7cNQHj8exHXgCgjKGRXb2fOyC8gZqmhp08RCKIXCfgkvP/9wId5I4tAywb/O3MCftID9fTx3swf/XJROkdA==,iv:XT8HKYbGHh6VKekHAg1fPKt+/hHaFnyGF6zvp9nf2/k=,tag:kUqnKG6Kr4aBC1E9DO5CJA==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SExrSHVsajlUMjhyRng0
            UzFsRjFPSVQxTHI3RGlFR1hRa0Zreld6VkdZCjJYMFlnSytKeHk0Q0F2azBCR3g3
            R3pqTU1ReG9RcGRvVGRXaW5scjNlUWMKLS0tIFYxOUhiajFPVVhabnJDaTR4alFQ
            Rzl4WE00c3JIeUtwNmkxQ09SeFJ3ODQKZWSL683pYNnXB29WsVaZv+pUv7asUmjt
            cFh2Y/roskmY4Nf9wfPb/6FxgVuiUO1sUNkmQjhZrL+Fq3xQPzBfCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:59:50Z"
    mac: ENC[AES256_GCM,data:/cUvv9kIo7eD2/yPFJRgOZRjFNJVUnh72tdxLm3sEBzWBHHS5RnO3avcBCfgW3oVeoPE2sv8nNA99ZHc0anwLsdmBYIxNX8ppc3LyfVzJ5TF5fogtdbWWik3begS73B9+Bqdkj3y11XE7nUUaPQw5joW5Ab6MCo2w58jDgfhxuk=,iv:coX9PITuEAlyXIH3mABtjOTCEBpsQLf9ttqplyo4yLM=,tag:dZcV3Dx7+fuohNgsApfziw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
