apiVersion: ENC[AES256_GCM,data:1Ag=,iv:2OMPVrQCU5WD1VuxhbfyTdlI6JvVsA+w289bHZtpf08=,tag:di2UQaYVYAi8weH7rWob1A==,type:str]
kind: ENC[AES256_GCM,data:b9xDy2jn,iv:q1F5R/QimDDMmSxSBhneVQCnwtCS2eR8Apn95lqx3lM=,tag:l44Yl6Mm5NiecfxA1L37hQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QOqZN+3YTQ==,iv:04qh8KDOBb+3zL7h4N44aCcltieRvAK57jBdsjD3J68=,tag:3/ymSI0Dwb0YuALmRIMmAA==,type:str]
    namespace: ENC[AES256_GCM,data:QKo2fc76G3gvJdpG6WvMcw==,iv:ivUzoSARSKYQXMXYThmK9E8j139rpqIx4RoGY+cDPTU=,tag:X1lNkkpaL1NqLdah+NWCqg==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:0pAnGusiVOYZmlfur7DS,iv:M3ZT6+XHG40HnzByGCq1R41TmJvboRVDfU/51vDbC2g=,tag:trRSlszyjl7zsu9J8zk6JA==,type:str]
    PGUSER: ENC[AES256_GCM,data:0S/78Fe62AUN3xAHjQkj,iv:Qqf3o1kLa/v/ao/o+lCA/0U0DAoOKmFqr37r8MNBy/M=,tag:WXsWHSICxhM06BLX4nYd3A==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:z1LkvKp6MsvkwXfbajw=,iv:GTFjVd0KKlto9k61DWyt/Y1fvdUDbudz5qUniKboGLo=,tag:lus0hpErBrCnBzrlFPYewQ==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOWZORExCNDkwR2FWVEtk
            eUNCdS9FL21pREQwS0QyQ1l1KzRRYms4RVFJCkE4Y3BlZ0Y0VkNBekVZR1pnQ3dB
            QldIMmtxZEtSTldXdU9Vd1BJd2tNVW8KLS0tIFJCNVZ5M29CUWh4SzA0UERrMlpu
            N0ZmVTA2bDZzeVhsaWlBaHVxVVFIU1kKS4Aj6S1YKXPYFhjSCMm71COCMfrlZsN5
            A7BHQ4ShGDKkKKA1aone3rY/QVnrltBp2xUkVY1PmEa5EzEQkCH3pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T21:03:31Z"
    mac: ENC[AES256_GCM,data:IEmuC4b/Xe2BCF0uKIMO53LNzClQ8zMWzYpw+rWAcPe2GLH3t1ulhCk+l2MFa9Y9/PwzgsjCGnOcylK/v5626W6jfblqCCqTsuefTh5lOY3eL7T/807Q3Ehi3TwGGjYvnI64PnzJm/ckTb+cX1t+neIMOhdoc7aenbYF7VV1/4c=,iv:Dn9FXVJMQw2O8iK8pXEU3W0BHru4y+riLrC4Svxt/TE=,tag:IbZdpQx6xW+u4a5saAWmqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
