apiVersion: ENC[AES256_GCM,data:EiE=,iv:aOoP5HsOH+iTvkGyLROKzDL8Hub8RbASTvccZl1/2o8=,tag:tf4b35UcWxpxHSxSv6ADpQ==,type:str]
kind: ENC[AES256_GCM,data:ZM1gjLcC,iv:JOnKGi1sf5qyy5TK66qhj5Hm1PZrGiFNEFR1YNTXEbI=,tag:iculEznYzYLMB37kFGo3aQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:os3z3YGuzw==,iv:OQU/MagJTqiTEUVbvAXllJ+HL4F5ImdlQ6KJrsFyyP4=,tag:TxVJClR6irhQlHkJdalazg==,type:str]
    namespace: ENC[AES256_GCM,data:SB9w0KCu7BGSIoncpUaaKA==,iv:inC6pum3BbtCcAJytARJGByo9ql5kqfSOZFPRdI651A=,tag:bo0wJhDdvnl8dSQdIiM+7g==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:UN129f0fEvJ5mYsZcdpb,iv:PmGZV7zDip43auOK9iWy0HeIAYw4IVaSocnyzoeglkg=,tag:UWd/qvf7xraWsMW/e9tcog==,type:str]
    PGUSER: ENC[AES256_GCM,data:iNjp4rt5cWza1l7/RYK+,iv:1FNe0cRtBCQVzQDEqGp64hcP7Udvi3XrBb9Rm4Y9XK8=,tag:9p+C87cr3ps4m7BOzNvkYw==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:JP8JjVPpzeuqxTqIOt0=,iv:adEFzp8rbdgyjZy9TJ6J2JGdHdKalhGVCxysZIIxm8Q=,tag:rG8YaRgXKrclcqZs0bvxnA==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4KzBWZWtFb25tVHQxeWp3
            eFJrYVBpNE81dmZrZ1Z2ZVUwUEJiV1hheUVNCkFsanhIS2kwakllbUJLanFzMFFY
            ZmZoOHg1ZzFadlhmUXQ5Mm8vdldDWEkKLS0tIExPSitDOWJTbVpaRy9pSkdweE4z
            cEVIbzk1WTM5djRJYWEzWGx1ZHU4L3MKLTmkjOowjHGxCbp8il4Ue/VJlmMHU4A/
            gJopaQnR/lyoer71O4EnQEPzZWF82cpXvsMV40kUi8659bO6XcfqdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:59:50Z"
    mac: ENC[AES256_GCM,data:Zw7kVEqEpg4kYD1iAODH7mS0bU0iHwu79lX3DoeV2EzYOqr9cos0jQWQi2grtlm/V8/U6eaXBRgDrQ194McswUHfPa5yBpFf3Ah1nVXOdgAduGzmXRV5bx6gsVjnMA958sqsB+dVAWGvkEuKQsIObewsKpHJuEK8pLcKs+M0c1g=,iv:iN2ln4UZ2t5XEgK24s57Ht7wSejtyxc88tKBnHJy0Ks=,tag:Lk2OTr9bN2wMdD0eUrjZ0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
