apiVersion: ENC[AES256_GCM,data:L00=,iv:ucTsYTCeGM2SoREksnWXL0U3DvgEheOIz0KiyqKin90=,tag:vBUDQkD0n1UKg6BHufeLGg==,type:str]
kind: ENC[AES256_GCM,data:OXNjcmB+,iv:Rt8730PHFBHtQD57Okf3+hmV+gdpaHT7gzs6LnGpRvk=,tag:vtxohFc/Z0uqG8ki7lTAfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BJE7EtPjHA==,iv:mtv5JbERkKEJCiaNW6jLN+oDYyqCXKyreXI3UyfPcMA=,tag:Kvp2XGVDJvsftsW/6sK9Jg==,type:str]
    namespace: ENC[AES256_GCM,data:QA6VNKbhJ69DzAsxFQ8PLw==,iv:vf+Pfp27DMkeq2aKBn46u8RutMeLyubfz/RFwwNYfCc=,tag:9avPeHygTAsMdQyh6L9M/g==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:bnIZjfgZVqALnCRj8xTw,iv:vyDCAuntHvEUCsKt7xQmGUTouJKycPohsKfv3pMtxn8=,tag:KZVLZmoewN3qTfrZi81/WA==,type:str]
    PGUSER: ENC[AES256_GCM,data:zfiyFwmEmUwpSilGlmEg,iv:X6HekxK4cxnIDd8N/aNjXXznO1Oo5W1h6I/Oexk/vRU=,tag:Yihp2XQdvLCSwUKAv4EYig==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:QreGjEfLBosB7F+ypF0=,iv:o2MfhA0xlBG7gm7Ns4brZnPzOdo94DUbED8TWy8614Y=,tag:U+xUOtxCLqARmJV9RUAAbw==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WFRjck1QL3pLczlSckha
            SENiSlUxMXdaYmozTDdtMm95M1JQUlNLUlhFCnNZWlIwUExJdFIwK2U0RVJUd1Q3
            amdSOVRLd3g4N1JxUHdXUzZudk9MZDQKLS0tIDduT2xGOHBUNHR1eUVaZnlrV3pB
            V0Y5Njcxa1kzV01JaFJBYThaNGpKbE0KA2rUtZaz5FKtBg1e13C9niqgvC5kM0CV
            uMnQy8pSCJZTZE7ydATRWrzQ9EBu/xElUlt5VWixXPXu4toHH13GOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-23T18:42:23Z"
    mac: ENC[AES256_GCM,data:ZQNztysmzeTTX3n93TOCa13v5T03B9puG8CgWZi4JQpq6HQjXH0PiMHm6a9qpXTvTOmbRC5Vtk1j/ThxGIMPpIYaSSVtKv/AjY/Rt1/ZxIy5nHWpKkslbskyCicpuSjbIUs3nqiutYJhD+3X/dNevLOgPbxJqea+0Cu2K31Mwwo=,iv:gd52WXUy5tJcez5W3/G7j5U47Qgl5snCeVtxYeV/yTE=,tag:mm4ir4o43hiDOPim+bkCJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
