apiVersion: ENC[AES256_GCM,data:u8w=,iv:kz/hemYNCz/SKnAvxQCciKKbNTNCt8zDqq8N42qkEzY=,tag:L7KHOwKE/QCbvlj2YPGZFA==,type:str]
kind: ENC[AES256_GCM,data:y7TNSiEY,iv:s49Se3vV6UIqFnQZHD2MCHsm1Aft9bxy4AG1yZF4dHc=,tag:7+Tlxxl7bp2BmyQYLEgMuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s2xv+PQ+QgpFjyRHyRs=,iv:HRZxeFuQlqF+akMbl8AUYYVTo+sO6H/HxUreyxvJq70=,tag:L39gVrIvJbb5O+fLKDG2WA==,type:str]
    namespace: ENC[AES256_GCM,data:Gge9z1gK6CTCPcfgjpUuCA==,iv:UqWrqtopP5/MPCrOcS1ZoTJiV/vpXiAOF7RrxN+23Go=,tag:8EydMayEtRSWvAhMD78u6Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:sQmXVE0ZiouQ,iv:8A0F5lpPYO6QQq7HaiFnRqMUWsI7sEP0w5wLwT+8s64=,tag:9R0ngMnhy/rhvhk+GMPiJw==,type:str]
    password: ENC[AES256_GCM,data:r79NspCi3yqdeQ==,iv:FH9hxwnSpJrqXiUrkxEPb6Vw8hmfA7Gx1eoXNX4IXe4=,tag:iQ8t8aLctk5+pozlbI9YPw==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjh3aTY5TEcwbnNQNmx3
            WGM0a2ZOT3pRcVAzdEdzRG0ydDl3aGFDa1RvClJDcmNmdFVsTHpRNlpXbVhyRVlo
            dm50eDRSaTYwUk5MYzVBQ3FxaWE2b1EKLS0tIEVRNU9XZDNPSzE2TlAzOFNuTnR6
            NUdrRkVSZU43T1dzWlR0Uk1GdTczYWsKR5QWdTZERFTfh6sBMD5SV6LzvHBP0XV9
            5cHO4hOp5QMQJxLMZB+kFlpPqMoFb/JNFq86+UQeIfsCm94nvXfEpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T08:46:38Z"
    mac: ENC[AES256_GCM,data:7wrI2GMNap6rGun/VBxEQuqHfDphYez0e16A8GXCyFk/VSUs0+ctPGZDfWfoXxvPCUnCyNMyPhuZBPtSG3JiyjxvAtQfu5fIs7848iBUW4L9hEi7wk23YUmZCqo8mggts95iowBi2HqrOdhZeL8JILc5UWTX2GzVYA0MEFizzFE=,iv:3zRsbGV3X0DLk9ZufEy7ka9zdS9z9SRAB9GkU/UUCtM=,tag:FGwdOPzPCI8981OYH2IH5g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
