apiVersion: ENC[AES256_GCM,data:pdY=,iv:/v/B+m/J+hTUciZ6UjYqhcCmJ48l8h0pjLF1kIwYZy0=,tag:DKcbvp7Lcrj5do1W3doPjQ==,type:str]
kind: ENC[AES256_GCM,data:jjypPmHO,iv:2zwBHkuUvKjd3zKu2hNUo9o6gAYrkb37t9Jf1H6H0DM=,tag:UCq/vLE3BepYiKAbxGUaoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ls+ewazZQQ==,iv:fTAP6JCZvOeJHFLPFW2kxL3EXYbh3NtuoPqfLRGzePc=,tag:8DvsOmrnzvbuenT/jqrOmQ==,type:str]
    namespace: ENC[AES256_GCM,data:qoQJLsNfOzkd1/bLxMmabQ==,iv:/vHWOUhULSx7BLWwIBfmrYvPm8880nGs0XYK90/WmDg=,tag:XNGNcQ/EcrGKc4zG0WBiwQ==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:Qat1knnlEwGNRDlpmuMe,iv:fPfqS0yOcUE9ir6n2YRMsoxON0C8xzI3FRfzOT/nlXE=,tag:VPfNanru91XdnTCuDEsjdg==,type:str]
    PGUSER: ENC[AES256_GCM,data:H6byeil5uvUk0yIpL18U,iv:WwaNoBuC91mdkg5d0nQjiln8hPaVyWYpPOOKf1x3c0M=,tag:rv3IFmGEVHqOGDsimfXnHw==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:JLF/pIjd8tJ8zwp0zyM=,iv:2CuBh0YXVQoiKZG+ZqMOH+mLpEZiz1WLvSYOfYieEmU=,tag:1mHhyXAxYei04lisP4kMWg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmY2d3ArU1FXT29oR1cr
            SXZrSU50ZnRQSjgyOEM4QktYNytKQjUxWFJNCmI5MEdHVkl1ZXB2aXZncGpqbm9h
            Z1AzamF6bnlEZjFrTDdlcFpGU0p1Z28KLS0tIG1wSlNlMHo2N3JEaWJ1VTBHUXdv
            UHE2dy9KNkY1a0NPUVYxTkwrWTBwWncK1jrkIVNBFMePRxr6yUgQZdqnNq2TVuGL
            XcbybbdFcjay528mjyAqjAbu8nyi4wCqtCLLt/hrO//39A5E5UkHbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T12:30:39Z"
    mac: ENC[AES256_GCM,data:lJfwQb4MIRMN6HTX0oOcw7m4x8BzEzJ8e8/sQFMGQwXWMhuwZFm8o2iDD0ErhntGtn2XGPmJ5268mC65mRiqzyQUmRTWv2HIG/Qmr4wEp/w2KuOUhxZjjmlOpXGpMq5DE/8hMOrEIuEIpeVLBoZnZNhtHgtgtbU3xE+MVR0COpE=,iv:eQlYD7pEF9uuzQKwrX7ZNPCx9ukYCdAcGTP7C+dIjJg=,tag:1YdROkzAwIAIvNV9Kz8Qwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
