apiVersion: ENC[AES256_GCM,data:WXc=,iv:jNXfuL3atQVfzx5GGY6PAjJY8DyQdP5nhYFQx1ua5Us=,tag:8xwMstXyQTsD3nqhH/6hLA==,type:str]
kind: ENC[AES256_GCM,data:VROe59nl,iv:4SatBl7O8Smgt3sOT3lwMWhd1lLB0gKuWvyC/hmV9PE=,tag:x8xqii8Qc+KvoniUYqTv2A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eg2a3/Fl+oo4olAzsEQ=,iv:QbsounQYQFWR/BTZZnsvnZkhppVknTq/k8vNMABll/w=,tag:iHIXXkBfCiJVF30vVi3Hfg==,type:str]
    namespace: ENC[AES256_GCM,data:zp08Z2l8egUzBYkscqf7qg==,iv:4dHbP3cIWmMJSfUurwr9nR18RSteH+YYrSxXnqPrJkY=,tag:xHaM1XVVSFw+FLjlseM9LA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:2eaFgO9Hh+Rb,iv:wXZ3Rf550jmb+LXxih7zsFRodUJ60c69rP/maFuATl8=,tag:vKzA8pUdYXtbKyJc+VH3Uw==,type:str]
    password: ENC[AES256_GCM,data:/arEVh8Vi9itDA==,iv:t5xixNWnePZK8Bvvy16m2lNR+BcKEu2HmJx7v/La5eM=,tag:z5gdMgVzLNL57d2Q0n2m9Q==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZG10YU1Yc2xCZ3FKZnJT
            Sy9aTnE0Z0c5cEpOcHB0bU5POHMvcXJ2eVFjClFWdHF4NkhuWFM5RkxHbnlSSXhy
            bkFvdGFZM0k3YmtXT2tQS3JKOXZWdkUKLS0tIDJkbjc2cG5ITTNFZ0FLWTNCcGQv
            WHRKa2dPQ2FuN1dsYzB4TWE3UC9NQUkKHoBPJuU+ooNqcpA3C0Yp2Naeo7IQ+7S8
            mHMD1y0QRvqDJ1T9sMmbMD9amRSPagOhtc7CyCYn4CEcy5AO0FCWZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:56:53Z"
    mac: ENC[AES256_GCM,data:sM5G4svFlCfgJMQoFM5TV5rltSypWDTZikIrr6bXEFRZzYyVZkvrWOKesSHWBh6VcDiKDq+3zhNss5nSk72JMxqYNTagD3fi7PTiZ4OJ+8Bem7bK0U08nrSYL1KsuK89HUcSDvslsM1SqWmKQWFHrLDfb75OyGOwtp9OKMQ6ll0=,iv:hGOeuXB4fX/eHAcuA/xbmey30PJaZkbDzHpayQJOzHE=,tag:AySi0N5kQjoMkNqlPJ5ApQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
