apiVersion: ENC[AES256_GCM,data:IJ0=,iv:/PE2fbSgAzhIb/A+krkux1yVgDC15LMNh0xjuvRo5cc=,tag:iQn6YukOM6fRjmR2VpqEng==,type:str]
kind: ENC[AES256_GCM,data:Ih3SlZJG,iv:NS6TGzVexnLntx3xQ9Ale7UseY1BR6haS0el2c4V6wU=,tag:hLTa+J15l5upA+CwtGpsHw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VZ4gSBp3bQ==,iv:HX4oFLAxfjxE9DaSjjHpTxbcsdofjH1Q5b3j8zMLug8=,tag:fXaCfb5DpHbzjmkn+NccAQ==,type:str]
    namespace: ENC[AES256_GCM,data:itZiD5cyAkbSQe/FJQ+Oag==,iv:E0ViTqBoramLD6a4k811e8PpkH1OBfcdcqoS/dAMDBI=,tag:eUAUGSqIZ9uRmkWhhW2qWQ==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:Rlt6971tDJvrmMET2J3u,iv:W1eiVv7BHpvHfQXSHCLfKf5dCHRyMpeG2mAWt8yXlh4=,tag:gx6n9OnuLxIo2SwOEq2Rvg==,type:str]
    PGUSER: ENC[AES256_GCM,data:Egxko088mzvOZOfowX2d,iv:Mij03ejPwp2QC23ATcS4nqEgKoNnmXk0BV12xZ5lgFo=,tag:pKCNyXE1TiHAkb//MXGi8w==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:MhPjMYUabQMREW+ie6g=,iv:BrFpoqBo1gq+FZRcneXmfu78oM8JEDP1V4ocftUqDVM=,tag:uT7AF3uXntcO0S6VTVMhdg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQlhzWXQvcUdhNEJPU2xx
            cXRLQmljZTgzdVdOd0dHSzh5ME1kbk9hNFNVCmRycG44aTZ6MHBmaDNTRXFIS2Rs
            cVBwWkYvYm5RbE9zbmxQY0sybWNsMEUKLS0tIERBQ05zZlIwVzhVMEt4UTY3QzIz
            ZklUZkFLZmgwYzhqUTlnWlZkTWNPY2sK8jQeQpKOf03FOwMaHpskEu5wbEqY7n/V
            W1dy0kYeovcRC6FkxQheS4+1F2J1znJC6/PlpVHrxhaGhGWFS9AjHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T08:46:38Z"
    mac: ENC[AES256_GCM,data:W1TavoayRuVGxO19FnWZcgHx7Aylz5Fdxtrb+xlS+kq0be8wfFkO5LJkwD6bE7MgUpJ4tQG392B2rSpnQUi+aMGf44pV5Xe5LrUFTiGI8dJhivOz/op4PuBup3ha3FBLMbj/H9NqCyCZ1BbJNXrGMZ2MFxEGbaiteuT1T0BzHMs=,iv:IwYCC7KWlTSmAwFlKn01aHOUp5qR/J/jFWaitAjiQfQ=,tag:a4jFW2dgn2QsoWc2PQN+Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
