apiVersion: ENC[AES256_GCM,data:9eU=,iv:Pk2FdZu+dG44j7GL/wBrQi6TcqJ/zEFkxJGT1B7rDf8=,tag:zUD9TI2WtJ32xVKpdoRxgA==,type:str]
kind: ENC[AES256_GCM,data:OJOONgvO,iv:PskrAA67cdEcasC7h7vrRS/6cN9RGCT/uCFh8fDXqIs=,tag:xTm92uKyDHksN+4130BkCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5AImt3Zq9j3R8Pw=,iv:TrtgVQEuefXs6YO6d/T+HHriQf4rCLSgBKwjR5YTpT0=,tag:WVyTvSg4oB9hy0g9dBcw+w==,type:str]
    namespace: ENC[AES256_GCM,data:wSHuodTeWzEXUEbeFTOmpw==,iv:9u75mfEcYPTbtDjaBjaF6M+kFVMC0WD6HteRhGacA0E=,tag:89bTGsGixiKou/UC3cqpFw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:GLl5Q+DREqs=,iv:5azyu5vrCyDLpm74kQATp9DA6JI9RnRsHbzRe+2ThZA=,tag:SyY8cAScAm5QQg1l7DLyHw==,type:str]
    password: ENC[AES256_GCM,data:Z6AJtXbae7U8GUVsr7t5JA==,iv:ym7iff91IPaLzZ9FVRybhuMn7a5kA2FdrEkYRz5si/A=,tag:OFeavg01LnbGLwGWXDRVQg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTzZkUXNCTEpzdFhUTWRw
            UFpDTSsxR1ZIczZ3M05lVUZzbzFEeXVlTTEwCklqeXMrdXFaaGQ3QzJDK2tYazlG
            YUU0MXdFQ0cvdDJ3Z3lqMW9SNU1wOXMKLS0tIDRtZmhFV3VlMnRVVnZIVmFzbmVR
            OThQVndZYktMWlJ3SzNTdVA1VlFXUEkKJkg0slXw+PYtV2QfgzEOQ6Jh2AJ/L0g0
            zuMwHpe9mD0jto/gGf9HQNk6Th5CesjoL4qBi1kQu6oJXVqEpSFlHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-22T18:29:34Z"
    mac: ENC[AES256_GCM,data:JiWuPqbP8+B3Xh77jTYfyR+isP7/OSXznmRc6SMfeEU35KGDiQn0oXP1xY6L1KxpErMmoR3RR6Zl/Eqnq/5boMAfRG6WBbKoCOtYmwZJxppdfyMxGKFHacZ8a6PO9aylGqLRnvJL3oMSGbR5svTNohsNQ5tk8jOR+N8Khk6tgcU=,iv:SFeBWNlSqzN3awkFTn3mmxr2NusnntdLUuWPesH+LGQ=,tag:zJ0FTI3GsKHP0nXhNEWSUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
