apiVersion: ENC[AES256_GCM,data:/HU=,iv:dSI5966OCiI2N9/zAwl2a6tPnfiFLEgcEwNVA08YeRg=,tag:TiW3KiepbygwHiO1UQ7vZg==,type:str]
kind: ENC[AES256_GCM,data:6iMFHPQV,iv:21I9+7JZ+9uO6w8VftU6cPyx79hJIPzz6Mp1s5YjKfI=,tag:Lhu4bG74KU7MHo4GvRUycQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bi/vXfryLA==,iv:MkjZXggsUgu4YJwUDxHzo5cX6NBXSfy2fW1QUVAysJc=,tag:EHKEW8avveYMZEL3Bp41Iw==,type:str]
    namespace: ENC[AES256_GCM,data:I99kMOVH1M9KqeQnJkA/OA==,iv:beKM/Dn0C6O7LpMRjmDzW6DfdZ4kA/uqlaprWCw6czs=,tag:gZ23JYrvE/sBPcHee70K2g==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:mKdHP9POvH0lrovCmw==,iv:uOhYLDi8iZcaUGLVFO8X0pRI/Vm6mj4raCR8R+BV41Q=,tag:B53qBHyDBvsO2YsZC3KDxg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:BNcSRgQsW2Pi0hmB1ztG57iLBuSsjAQu5GV3o4Yp9QbCbhwHBl6oWE4t2Obr3rK9keEhYNtUqcerrUt409q3oQ==,iv:zIOsZ91TiPHB0g984H+QzllYo0ST0QfrZAp7WroTaFE=,tag:XCvq6LUsvNKzF3l/neoXGw==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcUk0NVlHVnNaM2FGSWRk
            RTR3d2I5SmxSQmo2UWhLZ3FXSVppWm9RS0hnCjVqTTkwQjAzc1orRmw2USs3Mm5u
            eGpUZDdjNk9qTUVlcWMrbXV6UU1KSUUKLS0tIDVValFueitRQmNuWEEveVpDYlVW
            RTJJVzJKeUZuKy9laStVRU5jdHlkL0kKn3E9T2ct6nXAzpFsB4sMJBeoIzZzvqDq
            1dC1x6eUIwBEDOpUoT/LrSQ6WeYGd9ZmBS+4iJA6gsm8/aD2vCqi0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T12:30:39Z"
    mac: ENC[AES256_GCM,data:+yRGbuV6LjRmmlnTo1fkm/5uBeoT1N+sT2taZ+9k2C3W5htubRQ/1BLEnJdVx7x56yVd9oPKJPvlXHJCzTZvP92bhDFcFHdDxA0pBdO+sPOniKNG2K3TykWXWcgVzQiw40pcJhHfBnVheLAnv46iEMj7dtU9bBRfPIKYvSXcKiM=,iv:IL/Aw6OifKFTRn1BYdLfVoiI5YGSfm1IpAqd3L4AbPw=,tag:yO9dKfYvC7F+0emRRZmYtg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
