apiVersion: ENC[AES256_GCM,data:sNo=,iv:xIMk8irhKYqu2Hgxv0fBxBpsU5V9BE5T1G7x8gkzTQ4=,tag:aS2woDb5C1K4n/NjqHNP7w==,type:str]
kind: ENC[AES256_GCM,data:i6Uqdkzr,iv:GAs+0mRuatRuSlryti8dUfgIlW1vGS8FFKBVCz3kLd4=,tag:fVrQJxmeCwdcD1JsKPGROQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pe/LYxksXo5+nUZ6SQM=,iv:xo/r26ohWp9DQm6taef+rkZ98OctwxgG71Gfmy6UKIw=,tag:KLMNSEug9oTPHPAvw4Sy7A==,type:str]
    namespace: ENC[AES256_GCM,data:oDM0ksl2THvbOuR2958zUg==,iv:A08631R+wu24tuhyoPFUQlwMAJyWPFS26tsVmCFIZ60=,tag:4bK7nfN2zf729PjyGiKWmw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:+1BP8ZhGgkE8,iv:lSY/INSWDqGw4zPEMSmRqlTpCFLaLOjubsUpwvpSGcw=,tag:QjX9b2rsrSJbuSnMJB8j+Q==,type:str]
    password: ENC[AES256_GCM,data:6qynESqIERyXkg==,iv:FclqecjNbdzWoUtKthc84oqCBWliz0tgobhtdfakyrc=,tag:V9IbRQC2CNOalvkYO+MphQ==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOFo0bUNTMVZiQThYSXd6
            WEVDSTZTeEo1YkJUZHVFVDhNeDhSRjVLM2dRCldGWjlzb1dnMUNyb0FCbTdUbUNT
            c0N4VDRWak0vbXJWZ1NmSkV4L0xzUEEKLS0tIFJCcnhHTU80T3NTemtzYkhoZTVs
            blBLWTcyc2NEallnT3NQYnJVSEdudGMKTCHIUpR408BkXgcmfTBHmzbHDCBVzyZG
            zOVonpGN3b6297UcKEHmMdNwATOZdzkf/onyRFX7mVeyyjJdwk7Uqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T12:59:50Z"
    mac: ENC[AES256_GCM,data:QmTxNCVVet3K9ahulakdiu0RATF3SH92ecbrCZsBorGgtxIxLQZGp6FPnBpl5KXkIDmOelBlYtjegAlkDS1QDSiGhuucsQJ2kNMdYaZh/P7MC5C8BXIc+OCAKS3HKH5UrZdlsxmLMjgPcc5lockYKVhg+jh01m2pidq4XeHE/e8=,iv:SR8PDnE6lguUHiTfCuD1XcU3dugK4Sw8AtfwzbPCbec=,tag:J+8qzAOZBbQ6f/kn4MUB8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
