apiVersion: ENC[AES256_GCM,data:QpU=,iv:TomR5F4Z87pmwNu+zifd9bJGqgBthFrstwN3M2TjJ1E=,tag:Tr8R41cUyrh+RvXulfaD+Q==,type:str]
kind: ENC[AES256_GCM,data:nHaznf/q,iv:SfmjH20Ip5VimPMj1fHVrzI0BM1HTG3unAI2mK1768M=,tag:/aU1QCbBny583DaFeDPakA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SavV8jBD+w==,iv:8DfnyzRyFa4t8D6NmHeaNwbaolkwg0qIAv32H43K1mM=,tag:w6MBSb8L5+65Ip1mIGAxcw==,type:str]
    namespace: ENC[AES256_GCM,data:bMyvbLhaXX1aT+LYBNjoXg==,iv:hHpBVIFnKZ7liKp/tHb4x1KsH5XWnovfKwwo1aypPeI=,tag:Z9CXJOF/4rDU/n0+gW6UfA==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:ayZYbcomrxUMSFCuPg==,iv:3t8dDgFIf2GtX44r+4byyQt5tgWr783hixATKLQWMTw=,tag:4p8oNVeq8VfVtr31QF7bFg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:AE3YeI/yG05oVkoJergQHW7xpogO8ETaXRYR3GlxbbrK7VvfZ/sgEVtDEA4+WXHdTII2SLM2UtlGI0KV+99+VA==,iv:DAZRN9ss+/Q3woQJDjDBS4N7xnUayqrDjbyOoltAZZM=,tag:3DMSedWyHXsBl2ymmTpzxg==,type:str]
sops:
    age:
        - recipient: age1tjkygqahtv3gxrktknq33gxuql70ax8mludhxd98q5fpl3veqfzs5ask40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbnZ6VFJTeFVsZTFWL1p0
            SXVRWmhqc2QrWkQ1Wm9tSzJEMWJpREhySFNrCjI3Rm0wVFNaM3ZwWmlJR3drN1Bm
            UVRJdURmR3hnc1BSSlVrU3c5dlZLcmMKLS0tIDV0OTArYlBIWi9kTU9nU2cwb3dX
            aWxKdWhGWks2TUVzWEljemx0Q2JiM2MKf5EJDGXI4DZVhRZp90O8t1wC2GwJw9fB
            cGwXPAPgZLmfzU+5ci9vK0nPJjB3RG5ZzN0eVKAXQ9mN7VhOQowIww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T10:00:32Z"
    mac: ENC[AES256_GCM,data:sQtbdCuUxzIq/RDk4vv0fc9nmaqWA3mpG/Q3n0ye3LTR13CK/hmgAHDVq2EgXSuYnNamUopPP9Wtukpx2Y+1by4bWa4CQA0uB3OD0o2HSVXrIUl1IxEu4g4dffUgZrOPj6NsO+M+hPyDedecSGy8OGxtfNG6TPoumXn8aZRaxOw=,iv:QyW5Gejiizj6iDjO0WCs8f+1LANaK6Ip0+B9lwn2hbg=,tag:LWA+0nGiGbuD94QFIMzD+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
