apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-usbmusic-smb
  namespace: reimagined-disco
spec:
  capacity:
    storage: 256G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    #- noperm
    #- mfsymlinks
    #- cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: usbmusic
    volumeAttributes:
      source: "//192.168.178.1/FRITZ.NAS" # MUSIC folder
    nodeStageSecretRef:
      name: smbcredentials
      namespace: reimagined-disco
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-usbmusic-smb
  namespace: reimagined-disco
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256G
  volumeName: pv-usbmusic-smb
  storageClassName: smb